### ISSUE TITLE
Error when opening map

### ISSUE THREAD

**Issue by ismail-doitbig** [CnCNet/WorldAlteringEditor#145]
![image](https://github.com/Rampastring/WorldAlteringEditor/assets/89635383/200f8105-d47c-4fc8-8243-a05d6556ec8d)
[[5] Snarks Second Tower Defense_b667cf10e1e2946f6105324d7d6479e14c904c68.zip](https://github.com/Rampastring/WorldAlteringEditor/files/14828151/5.Snarks.Second.Tower.Defense_b667cf10e1e2946f6105324d7d6479e14c904c68.zip)

**Comment by vanana-old-acc** [comment]
It may be better to just display these minor map ini errors in a dialog box similar to the error/warning box upon saving

**Comment by ZivDero** [comment]
> It may be better to just display these minor map ini errors in a dialog box similar to the error/warning box upon saving

It is by design that this crashes the editor. It is left to the user to fix issues with rules.

**Comment by ismail-doitbig** [comment]
This map is runnable in cncnet so it should be editable?

It would make sense if it doesn't run in cncnet that it would be uneditable until it's fixed

But if it runs in cncnet there's no reason it shouldn't run in the editor

**Comment by ZivDero** [comment]
> This map is runnable in cncnet so it should be editable?
> 
> It would make sense if it doesn't run in cncnet that it would be uneditable until it's fixed
> 
> But if it runs in cncnet there's no reason it shouldn't run in the editor

There are certain bugs that the game tolerates, but the editor does not. This is per design. Fix the bug (in this case, list the weapon)

**Comment by ismail-doitbig** [comment]
I'm not the original editor of this map and i dont know what to even put there. I'm just trying to edit someone else's map.

Probably it's some dead code from him.

So you're saying this is a WONTFIX ?

It would be nicer if the editor was as flexible as the game itself

**Comment by ZivDero** [comment]
> I'm not the original editor of this map and i dont know what to even put there. I'm just trying to edit someone else's map.
> 
> Probably it's some dead code from him.
> 
> So you're saying this is a WONTFIX ?
> 
> It would be nicer if the editor was as flexible as the game itself

This was discussed but was decided that the current approach is better, so yes, this is WAD.
The weapon that something is upposed to use is non-existent, so just change it.

**Comment by Rampastring** [comment]
Generally WAE uses a "fail fast" design, iow. if something is misconfigured, it gives an error instead of working around them.

This is usually helpful also to users because it allows them to get quickly informed of mistakes in their INI code. In this case, if the author of the map used WAE, they would have been aware of their missing weapon definition.

However, this design is a bit of a problem when editing existing community maps with flawed code. Especially if they are opened by someone who is not very familiar with INI configuration.

In this case, it can be fixed by opening the map file in Notepad, searching for the flawed weapon (`BlackHawkGun`), deleting the found `ElitePrimary=BlackHawkGun` INI key entry, and saving the map.

The resulting map can be opened in WAE.

@ismail-doitbig I've attached the fixed map below:

[b667cf10e1e2946f6105324d7d6479e14c904c68.zip](https://github.com/Rampastring/WorldAlteringEditor/files/14994295/b667cf10e1e2946f6105324d7d6479e14c904c68.zip)

**Comment by ismail-doitbig** [comment]
if this is WAD i'll close it
